include:
  - _pages

# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Conner Wilczewski
title: Computer Engineer
email: Wilczew9@msu.edu
# email_title: Email (Email title override)
phone: 248-639-9659
# phone_title: Phone (Phone title override)


# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  Conwilcz
facebook_username: conner.wilczewski

# Additional icon links
# additional_links:
# - title: Link name
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/me.jpg 
about_content: | # this will include new lines to allow paragraphs
  Since a young age, I've watched as technology continued to grow more advanced.  One leap of faith in dual enrollment of a computer networking class in highschool later,


  Since a young age, I've watched as technology would continue to grow more advanced, curiosity building more and more as the years went by. 
  In highschool, I took a leap of faith and decided to dual enroll in highschool, and a technical campus where I would spend my time learning about 
  
# so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#  - Lists
#  - Tables
#  - <a href="google.com">Links</a>
#  - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Caddying
        additional_links:
          - title:  For more on caddying...
            icon: fab fa-github
            url: https://www.usga.org/content/dam/usga/pdf/host-sites/Caddies.pdf
        sub_title: Honor's Caddy
        caption: (June 2016 - present) 
        description: | # this will include new lines to allow paragraphs
          - Skilled in assisting golf players by carrying bags, providing accurate yardage, advising on club selection, and reading greens. 
          - Proficient in maintaining a high standard of etiquette and supporting players in strategic game decisions. 
          - Demonstrated ability to build rapport with club members, enhancing their golfing experience and upholding the club’s reputation for exceptional guest service.
          
          
          ![alt text](/images/golfing.jpg "golfcourse")
  - title: Education
    layout: list
    content:
      - layout: left
        title: Michigan State University
        sub_title: Senior in Computer Engineering
        caption: (eg. 2021 - present)
        description: | # this will include new lines to allow paragraphs
          Computer engineering involves different aspects of technology, one of the most noticeable being circuitry and the understanding of electrical engineering principles and their applications. 
          Another important facet is the computer side of engineering, the programming and interworking's behind technology. 
          Every course has been instrumental in the broadening of my understanding of computer engineering, and led to the further interest of where technology will go next.

  
                      
          ![alt text](/images/msueduc.jpg "campus")

  - title: Projects
    layout: list
    content:
      - layout: left
        title: ATM Design
        sub_title: Developer
        caption: Spring 2024
        description: | # this will include new lines to allow paragraphs
          -	Collaborated with other students to create a mobile game using the MIT app Innovator
          -	Drove the project with guidance and teamwork building

      - layout: left
        title: Beta Tester
        sub_title: Game Tester
        caption: Summer 2023
        description: | # this will include new lines to allow paragraphs
          -	Provided constructive feedback regularly and checked for any bugs in a now released game

      - layout: left
        title: Game Design
        sub_title: Developer
        caption: Winter 2021
        description: | # this will include new lines to allow paragraphs
          -	Created an ATM in Verilog code that fully simulates an ATM’s transfer, deposit, withdraw, and option to pay debt
          -	Coded all potential possible outcomes including invalid funds for withdrawal or processing of different deposit amounts
        
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Speaking:** Back in highschool, I was apart of a competitive speaking club, which was apart of the **Michigan Interscholastic Forensics Association** (MIFA). 
      In my junior and senior year, I went on to states and obtained **5th** place overall in my catagory, oratory.


      **Handiwork:** In my free time, I help out with fundraisers for local charities. These fundraisers include all sorts of actvities per charity. My favorite local charity is the **Walled Lake Civic Fund**, as all proceeds go to a huge firework show for all residents and friends of Walled Lake!
      
      **Technical:** Circuit Analysis, Digital Circuit Design,  Circuit Troubleshooting, Computer Partitioning, Computer Troubleshooting

      **Software:** Keil, MATLAB, PSPICE, Vivado, Microsoft Word

      **Programming Language:** Python (Intermediate), C++ (Intermediate), Verilog (Intermediate)

      **Language:** English (Native), Japanese (beginner), Hawaiian (beginner)

      **Certifications:** Living Online - 2019,  Computing Fundamentals - 2019

      If you are curious to learn more about me and what I do in my free time, feel free to explore [more about me and my hobbies!](https://conw266.github.io/)
   
      

          


          

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
